### ISSUE TITLE
manage profile - approval and membership attributes missing (re-opened)

### ISSUE THREAD

**Issue by zen37** [thedoctor27/Zen33-Activities-SLN#13]
**admin can see them**

<img width="250" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/60b765e0-932f-4319-ad8e-b37e4c42854c">

**user cannot**

<img width="293" alt="image" src="https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/43f59f64-250a-40d5-afe1-7cb8cd923355">

**Comment by thedoctor27** [comment]
fixed

**Comment by zen37** [comment]
not fixed


![image](https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/7d9b44cd-b17a-4f70-9fb8-b67c13399f35)


![image](https://github.com/thedoctor27/Zen33-Activities-SLN/assets/17958527/b0cc10a2-ddcf-4a8e-8787-363e1584aea5)

**Comment by zen37** [comment]
not fixed, see above

**Comment by thedoctor27** [comment]
yes, the user connot set the approval options of his own profile, only admin can

**Comment by zen37** [comment]
yes, they cannot set it so read-only but they should be able to view them, for example if profile has not been approved, to see the reason why

**Comment by thedoctor27** [comment]
fixed
